Repository ngx-semantic/ngx-semantic-docs, pull requests merged in 2020-10, with the labels that each got.

#10 closes #7 | add divider documentation
  angular.json
  package.json
  src/app/app.module.ts
  src/app/components/doc-page-header.component.ts
  src/app/pages/elements/buttons/buttons.component.html
  src/app/pages/elements/divider/divider.component.html
  src/app/pages/elements/divider/divider.component.ts
  yarn.lock
Labels: documentation

#12 closes #8 | add auto deploy
  .travis.yml
  package.json
Labels: chore

#11 Docs Update
  .travis.yml
  src/app/pages/elements/headers/headers.component.html
  src/app/pages/elements/inputs/inputs.component.html
  src/app/pages/elements/labels/labels.component.html
  src/app/pages/elements/lists/lists.component.html
  src/app/pages/elements/loaders/loaders.component.html
  src/app/pages/elements/placeholders/placeholders.component.html
  src/app/pages/elements/rails/rails.component.html
  src/app/pages/elements/reveals/reveals.component.html
  src/app/pages/elements/segments/segments.component.html
  src/app/pages/elements/steps/steps.component.html
  src/app/pages/elements/steps/steps.component.ts
Labels: documentation

#14 closes #13 | complete buttons documentation
  package.json
  src/app/components/code-sample.component.ts
  src/app/pages/elements/buttons/buttons.component.html
  src/app/pages/elements/buttons/buttons.component.ts
  yarn.lock
Labels: documentation

#15 closes #9 | improve GitHub pages experience
  .travis.yml
  package.json
  src/app/pages/elements/buttons/buttons.component.html
  yarn.lock
Labels: enhancement

#16 ft: add container documentation
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/pages/elements/container/container.component.html
  src/app/pages/elements/container/container.component.scss
  src/app/pages/elements/container/container.component.ts
Labels: documentation

#17 Flag Documentation
  src/app/pages/elements/flags/flags.component.html
  src/app/pages/elements/flags/flags.component.ts
Labels: documentation, enhancement

#24 Labels Documentation
  src/app/pages/elements/labels/labels.component.html
  src/app/pages/elements/labels/labels.component.ts
Labels: documentation
