Repository ngx-semantic/ngx-semantic-docs, pull requests merged in 2021-05, with the labels that each got.

#91 closes #20 | add image docs
  package.json
  src/app/pages/elements/buttons/button.component.html
  src/app/pages/elements/buttons/button.component.scss
  src/app/pages/elements/buttons/button.component.ts
  src/app/pages/elements/container/container.component.html
  src/app/pages/elements/container/container.component.ts
  src/app/pages/elements/divider/divider.component.html
  src/app/pages/elements/divider/divider.component.ts
  src/app/pages/elements/elements-routing.module.ts
  src/app/pages/elements/elements.module.ts
  src/app/pages/elements/flag/flag.component.html
  src/app/pages/elements/flag/flag.component.scss
  src/app/pages/elements/flag/flag.component.ts
  src/app/pages/elements/flag/flags.component.ts
  src/app/pages/elements/header/header.component.html
  src/app/pages/elements/header/header.component.scss
  src/app/pages/elements/header/header.component.ts
  src/app/pages/elements/icon/icon.component.html
  src/app/pages/elements/icon/icon.component.scss
  src/app/pages/elements/icon/icon.component.ts
  src/app/pages/elements/image/image.component.html
  src/app/pages/elements/image/image.component.ts
  src/app/pages/elements/input/input.component.html
  src/app/pages/elements/input/input.component.ts
  src/app/pages/elements/placeholder/placeholders.component.ts
  src/app/shared/components/base-page.component.ts
  yarn.lock
Labels: documentation, enhancement

#93 closes #77 | add segment docs
  package.json
  src/app/pages/elements/elements-routing.module.ts
  src/app/pages/elements/elements.module.ts
  src/app/pages/elements/placeholder/placeholder.component.html
  src/app/pages/elements/placeholder/placeholder.component.scss
  src/app/pages/elements/placeholder/placeholder.component.ts
  src/app/pages/elements/segment/segment.component.html
  src/app/pages/elements/segment/segment.component.scss
  src/app/pages/elements/segment/segment.component.ts
  src/app/pages/elements/segment/segments.component.html
  src/app/pages/elements/segment/segments.component.ts
  src/app/shared/components/base-page.component.ts
  src/app/shared/components/doc-wireframe.component.ts
  yarn.lock
Labels: documentation, enhancement

#94 closes #57 | add breadcrumb docs
  src/app/pages/collections/breadcrumb/breadcrumb.component.html
  src/app/pages/collections/breadcrumb/breadcrumb.component.ts
  src/app/pages/collections/collections.module.ts
Labels: enhancement

#97 closes #23 | add list documentation
  src/app/pages/elements/list/list.component.html
  src/app/pages/elements/list/list.component.ts
Labels: documentation

#98 closes #50 | add search docs
  package.json
  src/app/app.component.html
  src/app/pages/collections/breadcrumb/breadcrumb.component.html
  src/app/pages/collections/messages/messages.component.ts
  src/app/pages/elements/header/header.component.ts
  src/app/pages/elements/icon/icon.component.ts
  src/app/pages/elements/placeholder/placeholder.component.ts
  src/app/pages/modules/dimmer/dimmer.component.ts
  src/app/pages/modules/embed/embed.component.ts
  src/app/pages/modules/modules-routing.module.ts
  src/app/pages/modules/modules.module.ts
  src/app/pages/modules/rating/rating.component.html
  src/app/pages/modules/rating/rating.component.ts
  src/app/pages/modules/search/search.component.html
  src/app/pages/modules/search/search.component.ts
  src/app/pages/modules/tab/tab.component.html
  src/app/pages/modules/tab/tab.component.ts
  yarn.lock
Labels: documentation, enhancement

#102 closes #6 | add contributing doc page
  src/app/app.component.html
  src/app/pages/general/contributing/contributing.component.html
  src/app/pages/general/contributing/contributing.component.ts
  src/app/pages/general/general-routing.module.ts
  src/app/pages/general/general.module.ts
  src/app/pages/general/quick-start/quick-start.component.ts
Labels: documentation, enhancement
